---
title: "R Notebook"
output: html_notebook
---
```{r include=FALSE}

library(tidyverse)
library(magrittr)
library(ggplot2)
library(readxl)
library(plyr)
library(scales)
library(webr)
library(dplyr)
library(lessR)




#.libPaths(new = "C:/Users/cast6/OneDrive/Documents/R/win-library/4.0")

#install.packages('lessR',dependencies = TRUE, repos='http://cran.rstudio.com/')



car_sales_df <- read_csv("car-sales.csv")
df.car_sales <- as.data.frame(car_sales_df)

#view(df.car_sales)

```
```{r }

ggplot(data=df.car_sales, aes(x=Make, y =Odometer)) + geom_bar(stat="identity") + ggtitle("Make of Vehicles Sold according to Odometer Mileage")

```




``` {r }

t <-table(df.car_sales$Colour)

# Getting color and converting into a number to be able to do math
r_names <- row.names(t)
tab_values <- as.numeric(t)

s_color_amount_df =  as.data.frame(cbind(Colors =r_names , Car_Amount = tab_values ))

s_color_amount_df <- transform(s_color_amount_df , Car_Amount = as.numeric(Car_Amount))


s_color_amount_df$fraction <- s_color_amount_df$Car_Amount / sum(s_color_amount_df$Car_Amount) 

s_color_amount_df
ggplot(s_color_amount_df, aes(x="" , y=Car_Amount, fill = Colors)) +
  scale_fill_manual(values=c("#454545", "#528AAE","#1A8719","#9E0000","#FFFFFF" ))+
  ggtitle("Percentage Of Cars Sold By Color")+
  geom_col(color = "black") + 
  geom_label(aes(label = percent(fraction)),
             position = position_stack(vjust = 0.5),
             show.legend = FALSE) +
  coord_polar("y")

```

```{r }

# Getting color and converting into a number to be able to do math

t_cars_type = table(df.car_sales$Make)

t_cars_type

r_type <- row.names(t_cars_type)
tab_t_values <- as.numeric(t_cars_type)


car_type_df =  as.data.frame(cbind(Make =r_type ,  Car_Amount = as.numeric(tab_t_values )))

car_type_num_df <- transform(car_type_df , Car_Amount = as.numeric(Car_Amount))




car_type_num_df$fraction <- car_type_num_df$Car_Amount / sum(car_type_num_df$Car_Amount) * 100

    

PieChart(Make,  y=Car_Amount, data = car_type_num_df, fill = "viridis",
         main = "Percentage of Cars Sold By Make", quiet=TRUE)
```


```{r }
car_sales_df <- read_csv("car-sales.csv")

ggplot(data = car_sales_df, aes(x = Make, y = Odometer, fill = Colour)) + 
geom_bar(stat="identity")+
ggtitle("Vehicles Sold by Odometer Reading and Color")+
scale_fill_manual(values=c("#1F211E", "#0014FB","#1A8719","#9E0000","#C3CDBE"))
```








